### ISSUE TITLE
zftftb_song_clust error

### ISSUE THREAD

**Issue by wingillis** [jmarkow/zftftb#3] opened 2015-04-17 16:27 UTC
``` matlab
Undefined function 'fieldnames' for input arguments of type 'double'.

Error in robofinch_extract_data (line 109)
                data_vars=fieldnames(y2);

Error in zftftb_song_clust (line 363)
            robofinch_extract_data(hits.ext_pts,hits.file_list,proc_dir,'audio_load',audio_load,'data_load',data_load,...

Error in fw_analysis (line 10)
zftftb_song_clust(pwd,'audio_load',audio_load,'data_load',data_load);
```

**Comment by jmarkow** [comment] 2015-04-20 14:40
This is due to data_load not returning a structure.  I've added an error that makes this more explicit to the user.  Considering this a documentation issue and not a bug, closing!

**Closed as completed by jmarkow** 2015-04-20 14:40 UTC
